// <auto-generated />
using MVC_UlkeVeBayraklar.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_UlkeVeBayraklar.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211115182619_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_UlkeVeBayraklar.Models.Entity.Renk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RenkAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Renkler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RenkAdi = "Siyah"
                        },
                        new
                        {
                            Id = 2,
                            RenkAdi = "Kahverengi"
                        },
                        new
                        {
                            Id = 3,
                            RenkAdi = "Gri"
                        },
                        new
                        {
                            Id = 4,
                            RenkAdi = "Beyaz"
                        },
                        new
                        {
                            Id = 5,
                            RenkAdi = "Sarı"
                        },
                        new
                        {
                            Id = 6,
                            RenkAdi = "Pembe"
                        },
                        new
                        {
                            Id = 7,
                            RenkAdi = "Mor"
                        },
                        new
                        {
                            Id = 8,
                            RenkAdi = "Mavi"
                        },
                        new
                        {
                            Id = 9,
                            RenkAdi = "Yeşil"
                        },
                        new
                        {
                            Id = 10,
                            RenkAdi = "Kırmızı"
                        });
                });

            modelBuilder.Entity("MVC_UlkeVeBayraklar.Models.Entity.Ulke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UlkeAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UlkeBayrak")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ulkeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UlkeAd = "Türkiye"
                        },
                        new
                        {
                            Id = 2,
                            UlkeAd = "Almanya"
                        },
                        new
                        {
                            Id = 3,
                            UlkeAd = "Fransa"
                        },
                        new
                        {
                            Id = 4,
                            UlkeAd = "İngiltere"
                        },
                        new
                        {
                            Id = 5,
                            UlkeAd = "Portekiz"
                        },
                        new
                        {
                            Id = 6,
                            UlkeAd = "İtalya"
                        },
                        new
                        {
                            Id = 7,
                            UlkeAd = "Belçika"
                        },
                        new
                        {
                            Id = 8,
                            UlkeAd = "Hırvatistan"
                        },
                        new
                        {
                            Id = 9,
                            UlkeAd = "Galler"
                        },
                        new
                        {
                            Id = 10,
                            UlkeAd = "Finlandiya"
                        },
                        new
                        {
                            Id = 11,
                            UlkeAd = "Rusya"
                        },
                        new
                        {
                            Id = 12,
                            UlkeAd = "Hollanda"
                        },
                        new
                        {
                            Id = 13,
                            UlkeAd = "Ukrayna"
                        },
                        new
                        {
                            Id = 14,
                            UlkeAd = "Avusturya"
                        },
                        new
                        {
                            Id = 15,
                            UlkeAd = "Kuzey Makedonya"
                        },
                        new
                        {
                            Id = 16,
                            UlkeAd = "İskoçya"
                        },
                        new
                        {
                            Id = 17,
                            UlkeAd = "Çekya"
                        },
                        new
                        {
                            Id = 18,
                            UlkeAd = "İsviçre"
                        },
                        new
                        {
                            Id = 19,
                            UlkeAd = "Danimarka"
                        },
                        new
                        {
                            Id = 20,
                            UlkeAd = "İspanya"
                        },
                        new
                        {
                            Id = 21,
                            UlkeAd = "Macaristan"
                        },
                        new
                        {
                            Id = 22,
                            UlkeAd = "Polonya"
                        },
                        new
                        {
                            Id = 23,
                            UlkeAd = "İsveç"
                        },
                        new
                        {
                            Id = 24,
                            UlkeAd = "Slovakya"
                        });
                });

            modelBuilder.Entity("UlkelerVeBayraklar", b =>
                {
                    b.Property<int>("RenkId")
                        .HasColumnType("int");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.HasKey("RenkId", "UlkeId");

                    b.HasIndex("UlkeId");

                    b.ToTable("UlkelerVeBayraklar");

                    b.HasData(
                        new
                        {
                            RenkId = 4,
                            UlkeId = 1
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 1
                        },
                        new
                        {
                            RenkId = 1,
                            UlkeId = 2
                        },
                        new
                        {
                            RenkId = 5,
                            UlkeId = 2
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 2
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 3
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 3
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 3
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 4
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 4
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 4
                        },
                        new
                        {
                            RenkId = 9,
                            UlkeId = 5
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 5
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 6
                        },
                        new
                        {
                            RenkId = 9,
                            UlkeId = 6
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 6
                        },
                        new
                        {
                            RenkId = 1,
                            UlkeId = 7
                        },
                        new
                        {
                            RenkId = 5,
                            UlkeId = 7
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 7
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 8
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 8
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 8
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 9
                        },
                        new
                        {
                            RenkId = 9,
                            UlkeId = 9
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 9
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 10
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 10
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 11
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 11
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 11
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 12
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 12
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 12
                        },
                        new
                        {
                            RenkId = 5,
                            UlkeId = 13
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 13
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 14
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 14
                        },
                        new
                        {
                            RenkId = 5,
                            UlkeId = 15
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 15
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 16
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 16
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 17
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 17
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 17
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 18
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 18
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 19
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 19
                        },
                        new
                        {
                            RenkId = 5,
                            UlkeId = 20
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 20
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 21
                        },
                        new
                        {
                            RenkId = 9,
                            UlkeId = 21
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 21
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 22
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 22
                        },
                        new
                        {
                            RenkId = 5,
                            UlkeId = 23
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 23
                        },
                        new
                        {
                            RenkId = 4,
                            UlkeId = 24
                        },
                        new
                        {
                            RenkId = 8,
                            UlkeId = 24
                        },
                        new
                        {
                            RenkId = 10,
                            UlkeId = 24
                        });
                });

            modelBuilder.Entity("UlkelerVeBayraklar", b =>
                {
                    b.HasOne("MVC_UlkeVeBayraklar.Models.Entity.Renk", null)
                        .WithMany()
                        .HasForeignKey("RenkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_UlkeVeBayraklar.Models.Entity.Ulke", null)
                        .WithMany()
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
